2013-12-12 15:49:45 Error: Fatal Error (1): Call to a member function find() on a non-object in [/home/vagrant/works/chatsystem/Controller/UsersController.php, line 7]
2013-12-12 15:49:45 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /users/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/home/vagrant/w...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/home/vagrant/w...', 7, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/home/vagrant/w...', 7, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 15:50:42 Error: Fatal Error (64): Cannot redeclare class Users in [/home/vagrant/works/chatsystem/Model/User.php, line 3]
2013-12-12 15:50:42 Error: [FatalErrorException] Cannot redeclare class Users
Request URL: /users/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', '/home/vagrant/w...', 3)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', '/home/vagrant/w...', 3, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', '/home/vagrant/w...', 3, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 15:54:50 Error: Fatal Error (1): Call to undefined function uses() in [/home/vagrant/works/chatsystem/Model/User.php, line 3]
2013-12-12 15:54:50 Error: [FatalErrorException] Call to undefined function uses()
Request URL: /users/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/home/vagrant/w...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/home/vagrant/w...', 3, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/home/vagrant/w...', 3, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 15:57:49 Error: Fatal Error (64): Cannot redeclare class Users in [/home/vagrant/works/chatsystem/Model/User.php, line 5]
2013-12-12 15:57:49 Error: [FatalErrorException] Cannot redeclare class Users
Request URL: /users/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', '/home/vagrant/w...', 5)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', '/home/vagrant/w...', 5, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', '/home/vagrant/w...', 5, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 16:08:48 Error: [MissingControllerException] Controller class MessageController could not be found.
Exception Attributes: array (
  'class' => 'MessageController',
  'plugin' => NULL,
)
Request URL: /message/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-12 16:11:11 Error: [MissingControllerException] Controller class MessageController could not be found.
Exception Attributes: array (
  'class' => 'MessageController',
  'plugin' => NULL,
)
Request URL: /message/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-12 16:11:14 Error: [MissingControllerException] Controller class MessageController could not be found.
Exception Attributes: array (
  'class' => 'MessageController',
  'plugin' => NULL,
)
Request URL: /message/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-12 16:14:12 Error: [MissingControllerException] Controller class MessageController could not be found.
Exception Attributes: array (
  'class' => 'MessageController',
  'plugin' => NULL,
)
Request URL: /message/index
Stack Trace:
#0 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-12 16:39:34 Error: [MissingActionException] Action MessagesController::view() could not be found.
Exception Attributes: array (
  'controller' => 'MessagesController',
  'action' => 'view',
)
Request URL: /messages/view/53
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#2 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-12 16:41:19 Error: [MissingViewException] View file "/home/vagrant/works/chatsystem/View/Messages/view.ctp" is missing.
Exception Attributes: array (
  'file' => '/home/vagrant/works/chatsystem/View/Messages/view.ctp',
)
Request URL: /messages/view/53
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/View/View.php(457): View->_getViewFileName(NULL)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(952): View->render(NULL, NULL)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#4 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-12-12 16:44:17 Error: [NotFoundException] Invalid Message
Request URL: /messages/view/5534
Stack Trace:
#0 [internal function]: MessagesController->view('5534')
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#4 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-12-12 16:54:52 Error: Fatal Error (4): syntax error, unexpected ')' in [/home/vagrant/works/chatsystem/Controller/MessagesController.php, line 29]
2013-12-12 16:54:52 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/home/vagrant/w...', 29)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/home/vagrant/w...', 29, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/home/vagrant/w...', 29, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 17:09:26 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(28): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:12:21 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(28): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:14:18 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(28): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:16:02 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(28): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:18:22 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(28): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:23:07 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(28): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:25:47 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(29): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:27:05 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(29): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:28:45 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(29): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:28:57 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(29): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:37:46 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(29): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:43:48 Error: Fatal Error (1): Call to a member function save() on a non-object in [/home/vagrant/works/chatsystem/Controller/ThreadsController.php, line 15]
2013-12-12 17:43:48 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /threads/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/home/vagrant/w...', 15)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/home/vagrant/w...', 15, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/home/vagrant/w...', 15, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 17:48:31 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `ch...', Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Datasource/DboSource.php(1003): DboSource->execute('INSERT INTO `ch...')
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Model/Model.php(1830): DboSource->create(Object(Message), Array, Array)
#4 /home/vagrant/works/chatsystem/Controller/MessagesController.php(28): Model->save(Array)
#5 [internal function]: MessagesController->add()
#6 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(MessagesController), Array)
#7 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MessagesController), Object(CakeRequest), Object(CakeResponse))
#9 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-12-12 17:52:41 Error: Fatal Error (4): syntax error, unexpected ')' in [/home/vagrant/works/chatsystem/Controller/MessagesController.php, line 28]
2013-12-12 17:52:41 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /messages/add
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/home/vagrant/w...', 28)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/home/vagrant/w...', 28, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/home/vagrant/w...', 28, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 18:44:00 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/home/vagrant/works/chatsystem/Controller/UsersController.php, line 8]
2013-12-12 18:44:00 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/home/vagrant/w...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/home/vagrant/w...', 8, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/home/vagrant/w...', 8, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 18:46:02 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/home/vagrant/works/chatsystem/Controller/UsersController.php, line 9]
2013-12-12 18:46:02 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/home/vagrant/w...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/home/vagrant/w...', 9, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/home/vagrant/w...', 9, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 18:46:03 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/home/vagrant/works/chatsystem/Controller/UsersController.php, line 9]
2013-12-12 18:46:03 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/home/vagrant/w...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/home/vagrant/w...', 9, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/home/vagrant/w...', 9, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 19:06:15 Error: Fatal Error (4): syntax error, unexpected ')', expecting '(' in [/home/vagrant/works/chatsystem/Model/User.php, line 55]
2013-12-12 19:06:15 Error: [FatalErrorException] syntax error, unexpected ')', expecting '('
Request URL: /users/login
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/home/vagrant/w...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/home/vagrant/w...', 55, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/home/vagrant/w...', 55, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-12 19:10:33 Error: [MissingControllerException] Controller class ChatboxController could not be found.
Exception Attributes: array (
  'class' => 'ChatboxController',
  'plugin' => NULL,
)
Request URL: /chatbox
Stack Trace:
#0 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-12 19:20:38 Error: [MissingControllerException] Controller class ChatboxController could not be found.
Exception Attributes: array (
  'class' => 'ChatboxController',
  'plugin' => NULL,
)
Request URL: /chatbox
Stack Trace:
#0 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-12 19:20:53 Error: [MissingActionException] Action ChatBoxController::index() could not be found.
Exception Attributes: array (
  'controller' => 'ChatBoxController',
  'action' => 'index',
)
Request URL: /ChatBox
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(ChatBoxController), Object(CakeRequest), Object(CakeResponse))
#2 /home/vagrant/works/chatsystem/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-12 19:21:16 Error: Fatal Error (1): Call to a member function find() on a non-object in [/home/vagrant/works/chatsystem/Controller/ChatBoxController.php, line 5]
2013-12-12 19:21:16 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /ChatBox/show
Stack Trace:
#0 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/home/vagrant/w...', 5)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/home/vagrant/w...', 5, Array)
#2 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/home/vagrant/w...', 5, Array)
#3 /home/vagrant/works/chatsystem/Vendor/pear-pear.cakephp.org/CakePHP/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
